name: Unity CI

on:
  push:
    branches:
      - main
      - dev

  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    name: Build Project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Cache Library
        uses: actions/cache@v4
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}

      - name: Run Unity Tests 
        uses: game-ci/unity-test-runner@v4 
        env: 
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }} 
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
